USE OceanViewResortDB;
GO

UPDATE Users
SET role = 'MANAGER'
WHERE UPPER(LTRIM(RTRIM(role))) IN ('ADMIN', 'MANAGER');

UPDATE Users
SET role = 'RECEPTIONIST'
WHERE UPPER(LTRIM(RTRIM(role))) IN ('STAFF', 'RECEPTIONIST');
GO
